"""Instagram educational perfumery ingredient pool — one ingredient per Reel."""

from __future__ import annotations

from typing import Any

INSTAGRAM_CONTENT_BRIEF = """INSTAGRAM PERFUMERY EDUCATION RULES:
Each 45-second video teaches ONE perfumery ingredient.

VIDEO STRUCTURE:
Clip 1 (15s):
  Show raw ingredient (flower, wood, resin, chemical bottle)
  Presenter says: 'Today we explore [INGREDIENT NAME]'
  'This comes from [ORIGIN] and smells like [SCENT PROFILE]'
  Close-up of ingredient texture and color

Clip 2 (15s):
  Show extraction process or usage in perfumery
  'Perfumers use this as a [top/heart/base] note'
  'Famous perfumes containing this: [examples]'
  Show perfume bottle or blending process

Clip 3 (15s):
  Fun fact that amazes viewers
  'Did you know: [FUN FACT]'
  'This is why [INGREDIENT] makes perfumes last longer/smell better'
  End: 'Follow for daily fragrance secrets! 🌸'

TITLE FORMAT:
- 'The $30,000/kg Ingredient in Your Favorite Perfume'
- 'Why Rose Absolute Costs More Than Gold'
- 'The Chemical That Makes Perfume Last All Day'
- 'This Whale Secretion Made Your Perfume Famous'
- 'The Flower That Only Blooms at Night for Perfumers'

CONTENT RULES:
- NEVER repeat an ingredient
- Always include origin country
- Always include scent description
- Always include at least one famous perfume
- Include one surprising/shocking fun fact
- End with: Follow for daily fragrance secrets!"""

INSTAGRAM_PERFUMERY_SETTINGS: tuple[str, ...] = (
    "elegant fragrance laboratory with amber bottles, glass pipettes, and warm golden lighting",
    "sophisticated perfume atelier with blotter strips, brass scales, and soft candle glow",
    "luxury fragrance studio with macro botanical displays and dark wood shelves",
    "mysterious ingredient vault with crystal bottles, resins, and rim lighting",
    "sunlit botanical workbench with fresh flowers, dried woods, and antique perfume organs",
)

INSTAGRAM_PERFUMERY_CTA = "Follow for daily fragrance secrets!"

INSTAGRAM_PERFUMERY_PRESENTER = (
    "elegant female fragrance educator — knowledgeable, passionate, sophisticated, "
    "teaches perfumery ingredients with warm golden lighting and macro elegance"
)

INSTAGRAM_PERFUMERY_POOL: tuple[dict[str, Any], ...] = (
    # --- ESSENTIAL OILS (20) ---
    {
        "ingredient_name": "Rose Absolute",
        "scientific_name": "Rosa damascena",
        "origin": "Bulgaria, Turkey, Morocco",
        "extraction_method": "solvent extraction",
        "scent_profile": "rich, honeyed, floral, slightly spicy",
        "perfume_role": "heart note",
        "famous_perfumes": ["Chanel No 5", "Joy by Jean Patou"],
        "fun_fact": "It takes 3-5 tons of rose petals to make 1kg of absolute",
        "category": "essential_oils",
    },
    {
        "ingredient_name": "Jasmine Absolute",
        "scientific_name": "Jasminum grandiflorum",
        "origin": "India, Egypt, France",
        "extraction_method": "solvent extraction",
        "scent_profile": "narcotic floral, creamy, indolic, slightly fruity",
        "perfume_role": "heart note",
        "famous_perfumes": ["Joy by Jean Patou", "Samsara by Guerlain"],
        "fun_fact": "Jasmine flowers must be hand-picked at night before the sun weakens their aroma",
        "category": "essential_oils",
    },
    {
        "ingredient_name": "Oud Wood",
        "scientific_name": "Aquilaria spp.",
        "origin": "Southeast Asia, Middle East",
        "extraction_method": "steam distillation",
        "scent_profile": "deep woody, animalic, balsamic, smoky",
        "perfume_role": "base note",
        "famous_perfumes": ["Oud Wood by Tom Ford", "Portrait of a Lady by Frederic Malle"],
        "fun_fact": "High-grade natural oud can cost more than gold by weight",
        "category": "essential_oils",
    },
    {
        "ingredient_name": "Sandalwood",
        "scientific_name": "Santalum album",
        "origin": "India, Australia",
        "extraction_method": "steam distillation",
        "scent_profile": "creamy, soft woody, milky, warm",
        "perfume_role": "base note",
        "famous_perfumes": ["Samsara by Guerlain", "Tam Dao by Diptyque"],
        "fun_fact": "Indian sandalwood trees must age about 15 years before harvest for quality oil",
        "category": "essential_oils",
    },
    {
        "ingredient_name": "Bergamot",
        "scientific_name": "Citrus bergamia",
        "origin": "Calabria, Italy",
        "extraction_method": "cold press",
        "scent_profile": "bright citrus, green, slightly floral, sparkling",
        "perfume_role": "top note",
        "famous_perfumes": ["Chanel No 5", "Eau Sauvage by Dior"],
        "fun_fact": "Almost all of the world's fine bergamot oil comes from a tiny coastal strip in Calabria",
        "category": "essential_oils",
    },
    {
        "ingredient_name": "Neroli",
        "scientific_name": "Citrus aurantium",
        "origin": "Tunisia, Morocco, Egypt",
        "extraction_method": "steam distillation",
        "scent_profile": "fresh floral citrus, green, slightly honeyed",
        "perfume_role": "heart note",
        "famous_perfumes": ["Cologne by Chanel", "Neroli Portofino by Tom Ford"],
        "fun_fact": "Neroli, petitgrain, and orange blossom absolute all come from the same bitter orange tree",
        "category": "essential_oils",
    },
    {
        "ingredient_name": "Lavender",
        "scientific_name": "Lavandula angustifolia",
        "origin": "France, Bulgaria, England",
        "extraction_method": "steam distillation",
        "scent_profile": "herbal, clean, soft floral, camphoraceous",
        "perfume_role": "heart note",
        "famous_perfumes": ["Pour Un Homme by Caron", "Jicky by Guerlain"],
        "fun_fact": "True lavender is a founding material of the classic fougère perfume family",
        "category": "essential_oils",
    },
    {
        "ingredient_name": "Ylang-Ylang",
        "scientific_name": "Cananga odorata",
        "origin": "Comoros, Madagascar, Philippines",
        "extraction_method": "steam distillation",
        "scent_profile": "sweet floral, banana-creamy, slightly spicy",
        "perfume_role": "heart note",
        "famous_perfumes": ["Chanel No 5", "Samsara by Guerlain"],
        "fun_fact": "Ylang-ylang oil is fractionated into Extra, I, II, and III grades for different perfume uses",
        "category": "essential_oils",
    },
    {
        "ingredient_name": "Patchouli",
        "scientific_name": "Pogostemon cablin",
        "origin": "Indonesia, India, Philippines",
        "extraction_method": "steam distillation",
        "scent_profile": "earthy, woody, damp, slightly sweet chocolate",
        "perfume_role": "base note",
        "famous_perfumes": ["Gentleman by Givenchy", "Aromatics Elixir by Clinique"],
        "fun_fact": "Patchouli leaves are traditionally fermented before distillation to deepen the aroma",
        "category": "essential_oils",
    },
    {
        "ingredient_name": "Vetiver",
        "scientific_name": "Chrysopogon zizanioides",
        "origin": "Haiti, Indonesia, India",
        "extraction_method": "steam distillation",
        "scent_profile": "smoky, earthy, woody, grapefruit-green",
        "perfume_role": "base note",
        "famous_perfumes": ["Vétiver by Guerlain", "Sycomore by Chanel"],
        "fun_fact": "Vetiver oil is distilled from the roots, not the grassy leaves above ground",
        "category": "essential_oils",
    },
    {
        "ingredient_name": "Geranium",
        "scientific_name": "Pelargonium graveolens",
        "origin": "Egypt, China, Reunion",
        "extraction_method": "steam distillation",
        "scent_profile": "rosy, green, minty-fresh, slightly lemony",
        "perfume_role": "heart note",
        "famous_perfumes": ["Paris by Yves Saint Laurent", "Geranium pour Monsieur by Frederic Malle"],
        "fun_fact": "Perfumers use geranium as a cheaper rosy accent when rose absolute is too costly",
        "category": "essential_oils",
    },
    {
        "ingredient_name": "Cedarwood",
        "scientific_name": "Cedrus atlantica",
        "origin": "Morocco, USA, China",
        "extraction_method": "steam distillation",
        "scent_profile": "dry woody, pencil-shaving, soft resinous",
        "perfume_role": "base note",
        "famous_perfumes": ["Fahrenheit by Dior", "Bois d'Argent by Dior"],
        "fun_fact": "Atlas cedar oil can contain up to 70% himachalenes — molecules that give it dry wood character",
        "category": "essential_oils",
    },
    {
        "ingredient_name": "Frankincense",
        "scientific_name": "Boswellia carterii",
        "origin": "Oman, Somalia, Ethiopia",
        "extraction_method": "steam distillation",
        "scent_profile": "resinous, citrus-pine, airy, incense-like",
        "perfume_role": "heart/base note",
        "famous_perfumes": ["Avignon by Comme des Garçons", "Encens Mythique by Guerlain"],
        "fun_fact": "Sacred frankincense trees are wounded by hand so the resin tears dry into golden tears",
        "category": "essential_oils",
    },
    {
        "ingredient_name": "Myrrh",
        "scientific_name": "Commiphora myrrha",
        "origin": "Somalia, Ethiopia, Yemen",
        "extraction_method": "steam distillation",
        "scent_profile": "bitter resinous, balsamic, warm, slightly medicinal",
        "perfume_role": "base note",
        "famous_perfumes": ["Myrrhe Impériale by Guerlain", "La Myrrhe by Serge Lutens"],
        "fun_fact": "Myrrh was once valued as highly as gold in ancient trade along the incense routes",
        "category": "essential_oils",
    },
    {
        "ingredient_name": "Benzoin",
        "scientific_name": "Styrax benzoin",
        "origin": "Laos, Thailand, Indonesia",
        "extraction_method": "solvent extraction",
        "scent_profile": "vanilla-sweet, balsamic, soft spicy, cozy",
        "perfume_role": "base note",
        "famous_perfumes": ["Shalimar by Guerlain", "Amber Absolute by Tom Ford"],
        "fun_fact": "Benzoin resin 'tears' form after the tree bark is carefully stripped in spiral cuts",
        "category": "essential_oils",
    },
    {
        "ingredient_name": "Labdanum",
        "scientific_name": "Cistus ladanifer",
        "origin": "Spain, Morocco, Portugal",
        "extraction_method": "solvent extraction",
        "scent_profile": "ambery, leathery, sweet resinous, animalic",
        "perfume_role": "base note",
        "famous_perfumes": ["Amber Absolute by Tom Ford", "Knize Ten"],
        "fun_fact": "In antiquity, labdanum was combed from goats' beards after they grazed rockrose shrubs",
        "category": "essential_oils",
    },
    {
        "ingredient_name": "Oakmoss",
        "scientific_name": "Evernia prunastri",
        "origin": "Yugoslavia region, France, Morocco",
        "extraction_method": "solvent extraction",
        "scent_profile": "forest floor, earthy, green-mossy, damp wood",
        "perfume_role": "base note",
        "famous_perfumes": ["Mitsouko by Guerlain", "Chypre by Coty"],
        "fun_fact": "Modern IFRA limits nearly ended classic chypre formulas built on oakmoss",
        "category": "essential_oils",
    },
    {
        "ingredient_name": "Orris Root",
        "scientific_name": "Iris pallida",
        "origin": "Italy, France, Morocco",
        "extraction_method": "steam distillation",
        "scent_profile": "powdery violet, woody, soft earthy butter",
        "perfume_role": "heart/base note",
        "famous_perfumes": ["Chanel's 31 Rue Cambon", "Iris Silver Mist by Serge Lutens"],
        "fun_fact": "Iris rhizomes are dried for 3–5 years before distillation — among perfume's longest waits",
        "category": "essential_oils",
    },
    {
        "ingredient_name": "Violet Leaf",
        "scientific_name": "Viola odorata",
        "origin": "Egypt, France, Italy",
        "extraction_method": "solvent extraction",
        "scent_profile": "green, leafy, cucumber-metallic, soft floral",
        "perfume_role": "heart note",
        "famous_perfumes": ["Chanel No 19", "Verdura by Ormonde Jayne"],
        "fun_fact": "Violet leaf absolute smells more like crushed green stems than sweet violet candy",
        "category": "essential_oils",
    },
    {
        "ingredient_name": "Clary Sage",
        "scientific_name": "Salvia sclarea",
        "origin": "France, Russia, Hungary",
        "extraction_method": "steam distillation",
        "scent_profile": "herbal, hay-like, soft amber, slightly winey",
        "perfume_role": "heart note",
        "famous_perfumes": ["Déclaration by Cartier", "Eau de Campagne by Sisley"],
        "fun_fact": "Clary sage can smell almost ambra-like when used as a softener in men's scents",
        "category": "essential_oils",
    },
    # --- AROMA CHEMICALS (15) ---
    {
        "ingredient_name": "Linalool",
        "scientific_name": "3,7-Dimethylocta-1,6-dien-3-ol",
        "origin": "Synthesized worldwide; natural in lavender and rosewood",
        "extraction_method": "synthesis / isolation",
        "scent_profile": "fresh floral, soft lavender, lightly citrus",
        "perfume_role": "heart note",
        "famous_perfumes": ["Chanel No 5", "CK One"],
        "fun_fact": "Linalool appears naturally in over 200 plants yet is one of the most used synthetics in perfume",
        "category": "aroma_chemicals",
    },
    {
        "ingredient_name": "Iso E Super",
        "scientific_name": "Tetramethyl acetyloctahydronaphthalenes",
        "origin": "Synthesized (IFF family)",
        "extraction_method": "chemical synthesis",
        "scent_profile": "velvety woody, transparent cedar, softly ambery",
        "perfume_role": "heart/base note",
        "famous_perfumes": ["Molecule 01 by Escentric Molecules", "Fahrenheit by Dior"],
        "fun_fact": "Some wearers can barely smell Iso E Super — yet others report it as magnetic skin scent",
        "category": "aroma_chemicals",
    },
    {
        "ingredient_name": "Ambroxan",
        "scientific_name": "Dodecahydro-3a,6,6,9a-tetramethylnaphtho[2,1-b]furan",
        "origin": "Synthesized from sclareol (clary sage)",
        "extraction_method": "semi-synthesis",
        "scent_profile": "warm ambergris, woody, mineral, radiant",
        "perfume_role": "base note",
        "famous_perfumes": ["Sauvage by Dior", "Another 13 by Le Labo"],
        "fun_fact": "Ambroxan became perfume's go-to ambergris replacement after whale hunting declined",
        "category": "aroma_chemicals",
    },
    {
        "ingredient_name": "Hedione",
        "scientific_name": "Methyl dihydrojasmonate",
        "origin": "Synthesized worldwide",
        "extraction_method": "chemical synthesis",
        "scent_profile": "transparent jasmine, airy, tea-like freshness",
        "perfume_role": "heart note",
        "famous_perfumes": ["Eau Sauvage by Dior", "CK One"],
        "fun_fact": "Hedione can increase perceived radiance so strongly some formulas use 20%+ of it",
        "category": "aroma_chemicals",
    },
    {
        "ingredient_name": "Galaxolide",
        "scientific_name": "1,3,4,6,7,8-Hexahydro-4,6,6,7,8,8-hexamethylcyclopenta[g]benzopyran",
        "origin": "Synthesized worldwide",
        "extraction_method": "chemical synthesis",
        "scent_profile": "clean white musk, powdery, soft laundry",
        "perfume_role": "base note",
        "famous_perfumes": ["White Musk by The Body Shop", "Alien by Mugler"],
        "fun_fact": "Galaxolide helped invent the modern 'clean skin' musk genre of the late 20th century",
        "category": "aroma_chemicals",
    },
    {
        "ingredient_name": "Ethylene Brassylate",
        "scientific_name": "1,4-Dioxacycloheptadecane-5,17-dione",
        "origin": "Synthesized worldwide",
        "extraction_method": "chemical synthesis",
        "scent_profile": "sweet musk, soft floral, creamy",
        "perfume_role": "base note",
        "famous_perfumes": ["Angel by Mugler", "Flowerbomb by Viktor & Rolf"],
        "fun_fact": "This macrocyclic musk is prized because it smells soft yet lasts for days on fabric",
        "category": "aroma_chemicals",
    },
    {
        "ingredient_name": "Isoeugenol",
        "scientific_name": "2-Methoxy-4-(prop-1-en-1-yl)phenol",
        "origin": "Isolated from clove / synthesized",
        "extraction_method": "isolation / synthesis",
        "scent_profile": "spicy clove, sweet woody, warm carnation",
        "perfume_role": "heart note",
        "famous_perfumes": ["Opium by Yves Saint Laurent", "Carnation classics"],
        "fun_fact": "Isoeugenol is restricted in modern formulas because it can trigger skin sensitization",
        "category": "aroma_chemicals",
    },
    {
        "ingredient_name": "Coumarin",
        "scientific_name": "2H-Chromen-2-one",
        "origin": "Synthesized; natural in tonka bean",
        "extraction_method": "chemical synthesis",
        "scent_profile": "hay-sweet, almond, warm vanilla tobacco",
        "perfume_role": "base note",
        "famous_perfumes": ["Fougère Royale by Houbigant", "Jicky by Guerlain"],
        "fun_fact": "Coumarin's 1882 synthesis launched modern synthetic perfumery with Fougère Royale",
        "category": "aroma_chemicals",
    },
    {
        "ingredient_name": "Vanillin",
        "scientific_name": "4-Hydroxy-3-methoxybenzaldehyde",
        "origin": "Synthesized; natural in vanilla pods",
        "extraction_method": "chemical synthesis",
        "scent_profile": "sweet vanilla, creamy, warm gourmand",
        "perfume_role": "base note",
        "famous_perfumes": ["Shalimar by Guerlain", "Spiritueuse Double Vanille"],
        "fun_fact": "Over 99% of the world's vanilla aroma now comes from synthetic vanillin, not pods",
        "category": "aroma_chemicals",
    },
    {
        "ingredient_name": "Eugenol",
        "scientific_name": "4-Allyl-2-methoxyphenol",
        "origin": "Clove bud oil / synthesis",
        "extraction_method": "isolation / synthesis",
        "scent_profile": "spicy clove, warm phenolic, slightly woody",
        "perfume_role": "heart note",
        "famous_perfumes": ["Opium by Yves Saint Laurent", "Youth-Dew by Estée Lauder"],
        "fun_fact": "Eugenol is why classic carnation perfumes smell like spicy pink florets",
        "category": "aroma_chemicals",
    },
    {
        "ingredient_name": "Citronellol",
        "scientific_name": "3,7-Dimethyloct-6-en-1-ol",
        "origin": "Rose and geranium oils / synthesis",
        "extraction_method": "isolation / synthesis",
        "scent_profile": "fresh rosy, citrus-green, soft petals",
        "perfume_role": "heart note",
        "famous_perfumes": ["Paris by Yves Saint Laurent", "Tea Rose classics"],
        "fun_fact": "Citronellol is one of the key molecules that make a perfume smell unmistakably rose",
        "category": "aroma_chemicals",
    },
    {
        "ingredient_name": "Geraniol",
        "scientific_name": "3,7-Dimethylocta-2,6-dien-1-ol",
        "origin": "Rose and palmarosa / synthesis",
        "extraction_method": "isolation / synthesis",
        "scent_profile": "sweet rose, geranium-green, softly citrus",
        "perfume_role": "heart note",
        "famous_perfumes": ["Tea Rose", "Paris by Yves Saint Laurent"],
        "fun_fact": "Geraniol and citronellol together rebuild most of rose's recognizable heart",
        "category": "aroma_chemicals",
    },
    {
        "ingredient_name": "Calone",
        "scientific_name": "7-Methyl-3,4-dihydro-2H-1,5-benzodioxepin-3-one",
        "origin": "Synthesized (marine note family)",
        "extraction_method": "chemical synthesis",
        "scent_profile": "ozonic, watery melon, sea breeze",
        "perfume_role": "top/heart note",
        "famous_perfumes": ["L'Eau d'Issey", "Acqua di Gio"],
        "fun_fact": "Calone invented the 1990s aquatic perfume boom with a single marine molecule",
        "category": "aroma_chemicals",
    },
    {
        "ingredient_name": "Dihydromyrcenol",
        "scientific_name": "2,6-Dimethyloct-7-en-2-ol",
        "origin": "Synthesized worldwide",
        "extraction_method": "chemical synthesis",
        "scent_profile": "fresh citrus-lime, clean laundry, metallic freshness",
        "perfume_role": "top note",
        "famous_perfumes": ["Cool Water by Davidoff", "CK One"],
        "fun_fact": "This molecule helped redefine men's cologne as bright, soapy, and sporty in the 1980s–90s",
        "category": "aroma_chemicals",
    },
    {
        "ingredient_name": "Iso Butavan",
        "scientific_name": "Isobutavan (ethyl vanillin related ester family)",
        "origin": "Synthesized worldwide",
        "extraction_method": "chemical synthesis",
        "scent_profile": "sweet vanilla, creamy, soft powdery gourmand",
        "perfume_role": "base note",
        "famous_perfumes": ["Angel by Mugler", "Black Orchid by Tom Ford"],
        "fun_fact": "Iso Butavan boosts vanilla trails without the sticky heaviness of raw vanillin alone",
        "category": "aroma_chemicals",
    },
    # --- CITRUS & TOP NOTES (10) ---
    {
        "ingredient_name": "Lemon",
        "scientific_name": "Citrus limon",
        "origin": "Italy, Spain, Argentina",
        "extraction_method": "cold press",
        "scent_profile": "sharp citrus zest, bright, juicy, slightly green",
        "perfume_role": "top note",
        "famous_perfumes": ["Eau Sauvage by Dior", "Light Blue by Dolce & Gabbana"],
        "fun_fact": "Cold-pressed lemon oil is phototoxic — high doses can burn skin in sunlight",
        "category": "citrus_top_notes",
    },
    {
        "ingredient_name": "Grapefruit",
        "scientific_name": "Citrus paradisi",
        "origin": "USA, Israel, South Africa",
        "extraction_method": "cold press",
        "scent_profile": "bitter citrus, sparkling, slightly sulfurous peel",
        "perfume_role": "top note",
        "famous_perfumes": ["CK One", "Ralph by Ralph Lauren"],
        "fun_fact": "Grapefruit's sharp bite comes partly from tiny amounts of nootkatone",
        "category": "citrus_top_notes",
    },
    {
        "ingredient_name": "Lime",
        "scientific_name": "Citrus aurantifolia",
        "origin": "Mexico, Brazil, Peru",
        "extraction_method": "cold press / distillation",
        "scent_profile": "zesty green citrus, tart, sparkling",
        "perfume_role": "top note",
        "famous_perfumes": ["Eau de Guerlain", "Acqua di Parma Colonia"],
        "fun_fact": "Distilled lime smells greener and less juicy than cold-pressed lime peel oil",
        "category": "citrus_top_notes",
    },
    {
        "ingredient_name": "Orange",
        "scientific_name": "Citrus sinensis",
        "origin": "Brazil, USA, Spain",
        "extraction_method": "cold press",
        "scent_profile": "sweet juicy citrus, sunny, soft peel",
        "perfume_role": "top note",
        "famous_perfumes": ["Joy by Jean Patou", "Orange Sanguine by Atelier Cologne"],
        "fun_fact": "Sweet orange oil is one of the cheapest natural citruses — yet still unlocks joyful openings",
        "category": "citrus_top_notes",
    },
    {
        "ingredient_name": "Mandarin",
        "scientific_name": "Citrus reticulata",
        "origin": "Italy, China, Spain",
        "extraction_method": "cold press",
        "scent_profile": "sweet citrus, soft candy-peel, gentle floral",
        "perfume_role": "top note",
        "famous_perfumes": ["Light Blue", "Mandarino di Amalfi by Tom Ford"],
        "fun_fact": "Green mandarin smells sharper than ripe mandarin — perfumers choose maturity deliberately",
        "category": "citrus_top_notes",
    },
    {
        "ingredient_name": "Petitgrain",
        "scientific_name": "Citrus aurantium",
        "origin": "Paraguay, France, Egypt",
        "extraction_method": "steam distillation",
        "scent_profile": "green woody citrus, leafy, soft floral",
        "perfume_role": "top/heart note",
        "famous_perfumes": ["Eau Sauvage", "Pour Monsieur by Chanel"],
        "fun_fact": "Petitgrain is distilled from leaves and twigs of the same tree that gives neroli flowers",
        "category": "citrus_top_notes",
    },
    {
        "ingredient_name": "Cardamom",
        "scientific_name": "Elettaria cardamomum",
        "origin": "India, Guatemala, Sri Lanka",
        "extraction_method": "steam distillation",
        "scent_profile": "spicy-fresh, eucalyptus-cool, softly sweet",
        "perfume_role": "top/heart note",
        "famous_perfumes": ["Déclaration by Cartier", "Déjà Vu White Flower 57 by Kayali"],
        "fun_fact": "Cardamom bridges citrus tops into spicy hearts without smelling like kitchen spice racks",
        "category": "citrus_top_notes",
    },
    {
        "ingredient_name": "Black Pepper",
        "scientific_name": "Piper nigrum",
        "origin": "India, Vietnam, Indonesia",
        "extraction_method": "steam distillation / CO2",
        "scent_profile": "sharp spicy, woody, dry, slightly citrus",
        "perfume_role": "top note",
        "famous_perfumes": ["Poivre Samarcande by Hermès", "Black Pepper by Molton Brown"],
        "fun_fact": "Freshly crushed black pepper oil smells more lemony than kitchen pepper dust suggests",
        "category": "citrus_top_notes",
    },
    {
        "ingredient_name": "Pink Pepper",
        "scientific_name": "Schinus molle / Schinus terebinthifolius",
        "origin": "Brazil, Peru, Reunion",
        "extraction_method": "steam distillation / CO2",
        "scent_profile": "rosy-peppery, soft spicy, lightly woody",
        "perfume_role": "top note",
        "famous_perfumes": ["Flowerbomb", "La Vie Est Belle"],
        "fun_fact": "Pink pepper isn't true pepper — it's a schinus berry that smells peppery-rosy",
        "category": "citrus_top_notes",
    },
    {
        "ingredient_name": "Blood Orange",
        "scientific_name": "Citrus sinensis var. sanguinelli",
        "origin": "Italy, Spain, California",
        "extraction_method": "cold press",
        "scent_profile": "sweet tart citrus, berry-tinged, juicy peel",
        "perfume_role": "top note",
        "famous_perfumes": ["Orange Sanguine by Atelier Cologne", "Light Blue Forever"],
        "fun_fact": "Blood orange's red flesh comes from anthocyanins — rare pigments in citrus peel oils",
        "category": "citrus_top_notes",
    },
    # --- MUSKS & BASE NOTES (10) ---
    {
        "ingredient_name": "White Musk",
        "scientific_name": "Synthetic macrocyclic / polycyclic musks",
        "origin": "Synthesized worldwide",
        "extraction_method": "chemical synthesis",
        "scent_profile": "clean soft skin, powdery, laundry-fresh",
        "perfume_role": "base note",
        "famous_perfumes": ["White Musk by The Body Shop", "Narciso Rodriguez for Her"],
        "fun_fact": "Almost all modern 'white musk' is synthetic — natural animal musk is virtually unused",
        "category": "musks_base_notes",
    },
    {
        "ingredient_name": "Ambergris",
        "scientific_name": "Ambrein-rich whale excretion",
        "origin": "Ocean-found; historically sperm whale",
        "extraction_method": "natural collection / tincture",
        "scent_profile": "marine salty, sweet tobacco, warm skin",
        "perfume_role": "base note",
        "famous_perfumes": ["Chanel No 5 (historic)", "Ambre Sultan by Serge Lutens"],
        "fun_fact": "True ambergris begins as a pathological mass from sperm whales, cured for years at sea",
        "category": "musks_base_notes",
    },
    {
        "ingredient_name": "Castoreum",
        "scientific_name": "Castor fiber / Castor canadensis secretion",
        "origin": "Historically Canada, Russia; now mostly synthetic",
        "extraction_method": "tincture / reconstruction",
        "scent_profile": "leathery, animalic, smoky, warm",
        "perfume_role": "base note",
        "famous_perfumes": ["Knize Ten", "Cuir de Russie by Chanel"],
        "fun_fact": "Castoreum once came from beaver castor sacs — today fragrance houses use reconstructions",
        "category": "musks_base_notes",
    },
    {
        "ingredient_name": "Civet",
        "scientific_name": "Civettictis civetta secretion",
        "origin": "Historically Ethiopia, Africa; now synthetic",
        "extraction_method": "tincture / synthesis",
        "scent_profile": "animalic, fecal-floral bloom when diluted, warm skin",
        "perfume_role": "base note",
        "famous_perfumes": ["Chanel No 5 (historic)", "Jicky by Guerlain"],
        "fun_fact": "In tiny doses civet becomes floral nectar; neat, it can smell shockingly animalic",
        "category": "musks_base_notes",
    },
    {
        "ingredient_name": "Benzyl Benzoate",
        "scientific_name": "Benzyl benzoate",
        "origin": "Synthesized; natural traces in balsams",
        "extraction_method": "chemical synthesis",
        "scent_profile": "soft balsamic, faintly sweet, nearly odorless solvent warmth",
        "perfume_role": "base / solvent fixative",
        "famous_perfumes": ["Many oriental balsamic formulas", "Youth-Dew family scents"],
        "fun_fact": "Perfumers use benzyl benzoate as a fixative that makes heavier notes cling longer",
        "category": "musks_base_notes",
    },
    {
        "ingredient_name": "Tonka Bean",
        "scientific_name": "Dipteryx odorata",
        "origin": "Venezuela, Brazil, Nigeria",
        "extraction_method": "solvent extraction / tincture",
        "scent_profile": "coumarin hay, almond vanilla, warm tobacco",
        "perfume_role": "base note",
        "famous_perfumes": ["Tonka Imperiale by Guerlain", "Homme by Yves Saint Laurent"],
        "fun_fact": "Tonka beans are often soaked in alcohol then dried to crystallize coumarin on the surface",
        "category": "musks_base_notes",
    },
    {
        "ingredient_name": "Peru Balsam",
        "scientific_name": "Myroxylon balsamum var. pereirae",
        "origin": "El Salvador, Central America",
        "extraction_method": "solvent extraction / distillation",
        "scent_profile": "vanilla-balsamic, soft spicy, warm resin",
        "perfume_role": "base note",
        "famous_perfumes": ["Shalimar", "Emeraude by Coty"],
        "fun_fact": "Despite the name, Peru balsam is mainly harvested in El Salvador, not Peru",
        "category": "musks_base_notes",
    },
    {
        "ingredient_name": "Styrax",
        "scientific_name": "Liquidambar spp. / Styrax",
        "origin": "Turkey, Honduras, Guatemala",
        "extraction_method": "solvent extraction",
        "scent_profile": "sweet resinous, spicy balsamic, lightly styrene",
        "perfume_role": "base note",
        "famous_perfumes": ["Opium", "Amber Absolute"],
        "fun_fact": "Styrax resin can smell almost plastic-styrene neat — dilution unlocks its balsamic warmth",
        "category": "musks_base_notes",
    },
    {
        "ingredient_name": "Olibanum",
        "scientific_name": "Boswellia spp.",
        "origin": "Oman, Somalia, Ethiopia",
        "extraction_method": "steam distillation / solvent",
        "scent_profile": "bright incense, lemon-pine resin, spiritual airiness",
        "perfume_role": "heart/base note",
        "famous_perfumes": ["Avignon", "Encens et Lavande by Serge Lutens"],
        "fun_fact": "Olibanum is another botanical name for frankincense — the sacred tears of Boswellia",
        "category": "musks_base_notes",
    },
    {
        "ingredient_name": "Cashmeran",
        "scientific_name": "1,2,3,5,6,7-Hexahydro-1,1,2,3,3-pentamethyl-4H-inden-4-one",
        "origin": "Synthesized worldwide",
        "extraction_method": "chemical synthesis",
        "scent_profile": "soft musky wood, spicy, cashmere-like warmth",
        "perfume_role": "heart/base note",
        "famous_perfumes": ["Cashmere Mist", "Molecole-style woody musks"],
        "fun_fact": "Cashmeran feels like fragrant cashmere fabric — soft, spicy, and intimate on skin",
        "category": "musks_base_notes",
    },
    # --- EXTRACTION METHODS (10) ---
    {
        "ingredient_name": "Steam Distillation",
        "scientific_name": "Hydrodistillation process",
        "origin": "Global perfume industry standard",
        "extraction_method": "steam distillation",
        "scent_profile": "captures volatile aromatic molecules with heat and steam",
        "perfume_role": "extraction technique",
        "famous_perfumes": ["Any rose otto perfume", "Classic lavender colognes"],
        "fun_fact": "Steam distillation built the entire essential-oil industry centuries before synthetics",
        "category": "extraction_methods",
    },
    {
        "ingredient_name": "Cold Press",
        "scientific_name": "Expression / cold pressing",
        "origin": "Mediterranean citrus orchards",
        "extraction_method": "cold press",
        "scent_profile": "bright zest oils from citrus peels without heat damage",
        "perfume_role": "extraction technique",
        "famous_perfumes": ["Eau de Cologne classics", "Eau Sauvage"],
        "fun_fact": "Heat would destroy citrus top notes — so peels are pressed cold to keep sparkle",
        "category": "extraction_methods",
    },
    {
        "ingredient_name": "Enfleurage",
        "scientific_name": "Fat-absorption fragrance capture",
        "origin": "Grasse, France",
        "extraction_method": "enfleurage",
        "scent_profile": "captures ultra-delicate floral notes ruined by heat",
        "perfume_role": "extraction technique",
        "famous_perfumes": ["Historic jasmine and tuberose extrait", "Grasse traditional florals"],
        "fun_fact": "Enfleurage pressed fresh flowers onto glass frames of fat — then washed with alcohol",
        "category": "extraction_methods",
    },
    {
        "ingredient_name": "CO2 Extraction",
        "scientific_name": "Supercritical carbon dioxide extraction",
        "origin": "Modern extraction laboratories worldwide",
        "extraction_method": "CO2 extraction",
        "scent_profile": "true-to-plant aroma, often greener and fresher than steam oil",
        "perfume_role": "extraction technique",
        "famous_perfumes": ["Modern botanical niche formulas", "Pepper and ginger CO2 scents"],
        "fun_fact": "Supercritical CO2 acts like a solvent then disappears as gas — no residue left behind",
        "category": "extraction_methods",
    },
    {
        "ingredient_name": "Solvent Extraction",
        "scientific_name": "Hexane/volatile solvent extraction",
        "origin": "Grasse and modern fragrance plants",
        "extraction_method": "solvent extraction",
        "scent_profile": "creates concrete then absolute — richer than most distillates",
        "perfume_role": "extraction technique",
        "famous_perfumes": ["Chanel No 5 jasmine/rose", "Joy by Jean Patou"],
        "fun_fact": "Most precious floral absolutes exist because solvent extraction replaced deadly enfleurage labor",
        "category": "extraction_methods",
    },
    {
        "ingredient_name": "Absolute Extraction",
        "scientific_name": "Alcohol wash of aromatic concrete",
        "origin": "France and global absolute makers",
        "extraction_method": "absolute extraction",
        "scent_profile": "highly concentrated floral/resinous essence used in fine fragrance",
        "perfume_role": "extraction technique",
        "famous_perfumes": ["Any rose absolute extraits", "Jasmine absolute couture perfumes"],
        "fun_fact": "An absolute is concrete washed in alcohol — removing waxes that would cloud perfume",
        "category": "extraction_methods",
    },
    {
        "ingredient_name": "Resinoid",
        "scientific_name": "Solvent extract of resins/gums",
        "origin": "Resin-producing regions and labs",
        "extraction_method": "resinoid process",
        "scent_profile": "thick balsamic extracts from frankincense, myrrh, benzoin, labdanum",
        "perfume_role": "extraction technique",
        "famous_perfumes": ["Oriental amber formulas", "Shalimar-type balsams"],
        "fun_fact": "Resinoids are often too sticky for distillation — solvent is the only way to capture them",
        "category": "extraction_methods",
    },
    {
        "ingredient_name": "Tincture",
        "scientific_name": "Alcohol maceration extract",
        "origin": "Historic apothecaries and perfume houses",
        "extraction_method": "tincture",
        "scent_profile": "gentle alcoholic extracts of ambergris, vanilla, musk, tonka",
        "perfume_role": "extraction technique",
        "famous_perfumes": ["Historic ambergris tincture perfumes", "Vanilla tincture orientals"],
        "fun_fact": "Before synthetics, houses aged ambergris and civet tinctures for years like fine wine",
        "category": "extraction_methods",
    },
    {
        "ingredient_name": "Headspace",
        "scientific_name": "Dynamic headspace / living flower capture",
        "origin": "Modern fragrance R&D labs",
        "extraction_method": "headspace",
        "scent_profile": "reconstructs the living air around a blooming flower",
        "perfume_role": "extraction technique",
        "famous_perfumes": ["Modern living-flower niche scents", "Headspace-inspired floral launches"],
        "fun_fact": "Headspace captures scent molecules hovering above a live flower without picking it",
        "category": "extraction_methods",
    },
    {
        "ingredient_name": "Molecular Distillation",
        "scientific_name": "Short-path / molecular distillation",
        "origin": "Modern aroma-chemical purification plants",
        "extraction_method": "molecular distillation",
        "scent_profile": "ultra-pure fractions with unwanted notes removed",
        "perfume_role": "extraction technique",
        "famous_perfumes": ["Refined citrus specialty materials", "High-purity sandalwood fractions"],
        "fun_fact": "Molecular distillation can purify oils under vacuum so heat-sensitive notes survive",
        "category": "extraction_methods",
    },
    # --- PERFUME FAMILIES (15) ---
    {
        "ingredient_name": "Oriental Family",
        "scientific_name": "Ambery / oriental olfactive family",
        "origin": "Perfume classification tradition (France)",
        "extraction_method": "composition family",
        "scent_profile": "vanilla, resins, spices, warm sensual amber",
        "perfume_role": "perfume family",
        "famous_perfumes": ["Shalimar by Guerlain", "Opium by Yves Saint Laurent"],
        "fun_fact": "Oriental (ambers) were the first 'warm skin' luxury signatures of modern perfume",
        "category": "perfume_families",
    },
    {
        "ingredient_name": "Floral Family",
        "scientific_name": "Floral olfactive family",
        "origin": "Perfume classification tradition",
        "extraction_method": "composition family",
        "scent_profile": "rose, jasmine, iris, soft petal bouquets",
        "perfume_role": "perfume family",
        "famous_perfumes": ["Chanel No 5", "Joy by Jean Patou"],
        "fun_fact": "Floral is the largest perfume family — nearly half of women's launches historically",
        "category": "perfume_families",
    },
    {
        "ingredient_name": "Woody Family",
        "scientific_name": "Woody olfactive family",
        "origin": "Perfume classification tradition",
        "extraction_method": "composition family",
        "scent_profile": "sandalwood, cedar, vetiver, dry forest woods",
        "perfume_role": "perfume family",
        "famous_perfumes": ["Santal 33", "Fahrenheit by Dior"],
        "fun_fact": "Woody scents dominate modern niche perfume because woods feel intimate and lasting",
        "category": "perfume_families",
    },
    {
        "ingredient_name": "Fresh Family",
        "scientific_name": "Fresh / citrus-aromatic family",
        "origin": "Cologne tradition of Cologne & Mediterranean",
        "extraction_method": "composition family",
        "scent_profile": "citrus, herbs, clean water, airy brightness",
        "perfume_role": "perfume family",
        "famous_perfumes": ["Eau de Cologne", "CK One"],
        "fun_fact": "Fresh families came from 18th-century cologne recipes built on citrus and herbs",
        "category": "perfume_families",
    },
    {
        "ingredient_name": "Chypre Family",
        "scientific_name": "Chypre olfactive family",
        "origin": "Named after Cyprus (Chypre)",
        "extraction_method": "composition family",
        "scent_profile": "bergamot top, floral heart, oakmoss-labdanum base",
        "perfume_role": "perfume family",
        "famous_perfumes": ["Mitsouko by Guerlain", "Chypre by Coty"],
        "fun_fact": "A true chypre needs the oakmoss–labdanum–bergamot triangle to feel complete",
        "category": "perfume_families",
    },
    {
        "ingredient_name": "Fougère Family",
        "scientific_name": "Fougère olfactive family",
        "origin": "France — Fougère Royale (1882)",
        "extraction_method": "composition family",
        "scent_profile": "lavender, coumarin, oakmoss, aromatic herbs",
        "perfume_role": "perfume family",
        "famous_perfumes": ["Fougère Royale", "Drakkar Noir"],
        "fun_fact": "Fougère means fern — yet ferns are nearly scentless; the family is an olfactory illusion",
        "category": "perfume_families",
    },
    {
        "ingredient_name": "Gourmand Family",
        "scientific_name": "Gourmand olfactive family",
        "origin": "Modern classification (1990s boom)",
        "extraction_method": "composition family",
        "scent_profile": "vanilla, caramel, chocolate, edible sweetness",
        "perfume_role": "perfume family",
        "famous_perfumes": ["Angel by Mugler", "Pink Sugar"],
        "fun_fact": "Angel (1992) reinvented perfume as dessert — launching the modern gourmand era",
        "category": "perfume_families",
    },
    {
        "ingredient_name": "Aquatic Family",
        "scientific_name": "Aquatic / ozonic family",
        "origin": "1990s marine synthetic boom",
        "extraction_method": "composition family",
        "scent_profile": "sea air, melon water, ozone, clean minerals",
        "perfume_role": "perfume family",
        "famous_perfumes": ["L'Eau d'Issey", "Acqua di Gio"],
        "fun_fact": "Aquatics barely existed before Calone taught perfume how to smell like ocean air",
        "category": "perfume_families",
    },
    {
        "ingredient_name": "Green Family",
        "scientific_name": "Green olfactive family",
        "origin": "Perfume classification tradition",
        "extraction_method": "composition family",
        "scent_profile": "cut grass, leaves, galbanum, crisp stems",
        "perfume_role": "perfume family",
        "famous_perfumes": ["Vent Vert by Balmain", "Chanel No 19"],
        "fun_fact": "Green notes can feel more expensive than florals because they evoke living plants instantly",
        "category": "perfume_families",
    },
    {
        "ingredient_name": "Leather Family",
        "scientific_name": "Cuir / leather olfactive family",
        "origin": "Russian leather & chypre-leather traditions",
        "extraction_method": "composition family",
        "scent_profile": "smoky birch, animalic suede, dry tannins",
        "perfume_role": "perfume family",
        "famous_perfumes": ["Cuir de Russie", "Knize Ten"],
        "fun_fact": "Historic leather scents used birch tar to recreate the smell of cured Russian leather",
        "category": "perfume_families",
    },
    {
        "ingredient_name": "Aromatic Family",
        "scientific_name": "Aromatic / herbal family",
        "origin": "Mediterranean herb tradition",
        "extraction_method": "composition family",
        "scent_profile": "lavender, rosemary, sage, thyme freshness",
        "perfume_role": "perfume family",
        "famous_perfumes": ["Pour Un Homme by Caron", "Déclaration by Cartier"],
        "fun_fact": "Aromatic herb blends define many classic men's colognes more than woods alone",
        "category": "perfume_families",
    },
    {
        "ingredient_name": "Aldehydic Family",
        "scientific_name": "Aldehydic floral family",
        "origin": "Champagne aldehydes of early 20th century",
        "extraction_method": "composition family",
        "scent_profile": "soapy sparkle, metallic floral frost, champagne lift",
        "perfume_role": "perfume family",
        "famous_perfumes": ["Chanel No 5", "White Linen by Estée Lauder"],
        "fun_fact": "Chanel No 5 made aldehydes famous — a soapy sparkle no flower can make alone",
        "category": "perfume_families",
    },
    {
        "ingredient_name": "Fruity Family",
        "scientific_name": "Fruity olfactive family",
        "origin": "Modern classification",
        "extraction_method": "composition family",
        "scent_profile": "peach, pear, berry, juicy lactones",
        "perfume_role": "perfume family",
        "famous_perfumes": ["Miss Dior Cherie", "Nina by Nina Ricci"],
        "fun_fact": "Peach lactones taught perfume how to smell juicy without smelling like juice cartons",
        "category": "perfume_families",
    },
    {
        "ingredient_name": "Powdery Family",
        "scientific_name": "Powdery / iris-violet family",
        "origin": "Iris and ionone tradition",
        "extraction_method": "composition family",
        "scent_profile": "orris, violet, makeup compact, soft talc",
        "perfume_role": "perfume family",
        "famous_perfumes": ["L'Heure Bleue", "Iris Silver Mist"],
        "fun_fact": "Powdery accords recreate the scent of vintage makeup drawers and soft lipstick cases",
        "category": "perfume_families",
    },
    {
        "ingredient_name": "Animalic Family",
        "scientific_name": "Animalic olfactive family",
        "origin": "Historic musk-civet-castoreum tradition",
        "extraction_method": "composition family",
        "scent_profile": "warm skin, musk, leather, intimate animal breath",
        "perfume_role": "perfume family",
        "famous_perfumes": ["Muscs Koublai Khan", "Jicky"],
        "fun_fact": "Animalic notes are why some vintage masterpieces smell 'alive' on warm skin",
        "category": "perfume_families",
    },
    # --- EXTRA to exceed 80 unique after EO/musk overlaps ---
    {
        "ingredient_name": "Tuberose",
        "scientific_name": "Polianthes tuberosa",
        "origin": "India, Mexico, France",
        "extraction_method": "solvent extraction",
        "scent_profile": "narcotic white floral, creamy, rubbery-sweet",
        "perfume_role": "heart note",
        "famous_perfumes": ["Fracas by Robert Piguet", "Carnal Flower by Frederic Malle"],
        "fun_fact": "Tuberose continues producing scent after cutting — called the harlot of perfumery",
        "category": "essential_oils",
    },
    {
        "ingredient_name": "Mimosa Absolute",
        "scientific_name": "Acacia dealbata",
        "origin": "France, India, Egypt",
        "extraction_method": "solvent extraction",
        "scent_profile": "honeyed yellow floral, powdery, soft almond",
        "perfume_role": "heart note",
        "famous_perfumes": ["Une Fleur de Cassie", "Champs-Elysées by Guerlain"],
        "fun_fact": "Mimosa flowers are so delicate that solvent extraction is almost the only viable path",
        "category": "essential_oils",
    },
    {
        "ingredient_name": "Ionone",
        "scientific_name": "Ionones (alpha/beta)",
        "origin": "Synthesized; irones related to orris",
        "extraction_method": "chemical synthesis",
        "scent_profile": "violet candy, soft wood, powdery iris",
        "perfume_role": "heart note",
        "famous_perfumes": ["Après L'Ondée", "violet soliflores"],
        "fun_fact": "Ionones temporarily fatigue your nose — violet scent seems to vanish then return",
        "category": "aroma_chemicals",
    },
)


def format_ingredient_summary(ingredient: dict[str, Any]) -> str:
    name = str(ingredient.get("ingredient_name") or "").strip()
    origin = str(ingredient.get("origin") or "").strip()
    scent = str(ingredient.get("scent_profile") or "").strip()
    return f"{name} from {origin} — smells {scent}"


def famous_perfumes_text(ingredient: dict[str, Any]) -> str:
    items = [str(item).strip() for item in (ingredient.get("famous_perfumes") or []) if str(item).strip()]
    return ", ".join(items)


def ingredient_memory_key(ingredient_name: str) -> str:
    return f"ingredient:{ingredient_name.strip().lower()}"


__all__ = [
    "INSTAGRAM_CONTENT_BRIEF",
    "INSTAGRAM_PERFUMERY_CTA",
    "INSTAGRAM_PERFUMERY_POOL",
    "INSTAGRAM_PERFUMERY_PRESENTER",
    "INSTAGRAM_PERFUMERY_SETTINGS",
    "famous_perfumes_text",
    "format_ingredient_summary",
    "ingredient_memory_key",
]
