from pathlib import Path
from datetime import datetime


IGNORE_DIRS = {
    "venv",
    ".venv",
    "__pycache__",
    ".git",
    "outputs",
    "node_modules",
    ".pytest_cache",
    ".mypy_cache",
    ".idea",
    ".vscode",
}

IGNORE_FILES = {
    ".DS_Store",
}


def should_ignore(path: Path) -> bool:
    parts = set(path.parts)

    if any(part in IGNORE_DIRS for part in parts):
        return True

    if path.name in IGNORE_FILES:
        return True

    return False


def scan_project(project_root: str = ".") -> dict:
    root = Path(project_root).resolve()

    folders = []
    files = []

    for item in root.rglob("*"):
        if should_ignore(item):
            continue

        relative_path = item.relative_to(root)

        if item.is_dir():
            folders.append(str(relative_path))
        elif item.is_file():
            files.append(str(relative_path))

    return {
        "project_root": str(root),
        "scanned_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "folders": sorted(folders),
        "files": sorted(files),
        "total_folders": len(folders),
        "total_files": len(files),
    }


def write_current_state(report: dict, output_path: str = "project_brain/current_state.md") -> None:
    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)

    lines = []

    lines.append("# PROJECT CURRENT STATE")
    lines.append("")
    lines.append(f"Generated at: {report['scanned_at']}")
    lines.append(f"Project root: `{report['project_root']}`")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- Total folders: {report['total_folders']}")
    lines.append(f"- Total files: {report['total_files']}")
    lines.append("")
    lines.append("## Folders")
    lines.append("")

    if report["folders"]:
        for folder in report["folders"]:
            lines.append(f"- `{folder}`")
    else:
        lines.append("- No folders found.")

    lines.append("")
    lines.append("## Files")
    lines.append("")

    if report["files"]:
        for file in report["files"]:
            lines.append(f"- `{file}`")
    else:
        lines.append("- No files found.")

    lines.append("")
    lines.append("## Notes")
    lines.append("")
    lines.append("- This report is generated by `core/project_scanner.py`.")
    lines.append("- Ignored folders: `venv`, `.venv`, `__pycache__`, `outputs`, `.git`, `node_modules`.")
    lines.append("- No code was changed by this scanner.")
    lines.append("")

    output.write_text("\n".join(lines), encoding="utf-8")


def run_scan(project_root: str = ".") -> dict:
    report = scan_project(project_root)
    write_current_state(report)
    return report


if __name__ == "__main__":
    result = run_scan(".")
    print("Project scan completed.")
    print(f"Folders: {result['total_folders']}")
    print(f"Files: {result['total_files']}")
    print("Report saved to: project_brain/current_state.md")